HogTown_MapScripts::
	.byte 0

HogTown_EventScript_Signpost::
	msgbox HogTown_Text_Signpost, MSGBOX_NPC
	end

HogTown_Text_Signpost::
	.string "University of Floresol\n"
	.string "Floresol Field\p"
	.string "'The Swamp'\p"
	.string "Only Feraligatrs get out alive... $"

HogTown_EventScript_Coach::
	msgbox HogTown_Text_Coach, MSGBOX_NPC
	end

HogTown_Text_Coach::
	.string "Nothing gets me more pumped\n"
	.string "for the regular season\p"
	.string "than a great scrimmage!\p"
	.string "Give it all you've got team!$"

HogTown_EventScript_Trainer::
	msgbox HogTown_Text_Trainer, MSGBOX_NPC
	end
HogTown_Text_Trainer::
	.string "I'm busy battling...\n"
	.string "Grab a seat in the bleachers.$"

HogTown_EventScript_DateBoy::
	msgbox HogTown_Text_DateBoy, MSGBOX_NPC
	end
HogTown_Text_DateBoy::
	.string "I am so nervous!\p"
	.string "Do you think she can tell I'm nervous?\p"
	.string "I hope she likes me!\p"
	.string "I hope she doesn't think I'm a loser!$"
	
HogTown_EventScript_DateGirl::
	msgbox HogTown_Text_DateGirl, MSGBOX_NPC
	end
HogTown_Text_DateGirl::
	.string "Won't he shut up and kiss\n"
	.string "me already?$"

HogTown_EventScript_OldMan::
	msgbox HogTown_Text_OldMan, MSGBOX_NPC
	end
HogTown_Text_OldMan::
	.string "I used to be a great trainer.\p"
	.string "But now I'm just a spectator.\p"
	.string "I can't even remember the last time\n"
	.string "I battled.$"

HogTown_EventScript_Couple::
	msgbox HogTown_Text_Couple, MSGBOX_NPC
	end
HogTown_Text_Couple::
	.string "We met here in college.\p"
	.string "Now, when we want a nice date,\n"
	.string "we come here to watch the battles.$"

HogTown_EventScript_FeraligatrRight::
	msgbox HogTown_Text_FeraligatrRight, MSGBOX_NPC
	end
HogTown_Text_FeraligatrRight::
	.string "Ferrrrralll\p"
	.string "GATRRRRR!$"

HogTown_EventScript_FeraligatrLeft::
	msgbox HogTown_Text_FeraligatrLeft, MSGBOX_NPC
	end
HogTown_Text_FeraligatrLeft::
	.string "Ferali... Gatr!\p"
	.string "FERALIGATR!$"

HogTown_EventScript_Totodile::
	msgbox HogTown_Text_Totodile, MSGBOX_NPC
	end
HogTown_Text_Totodile::
	.string "Totodile!\n"
	.string "Totodile! Totodile\p"
	.string "Totodile!$"

HogTown_EventScript_Totodile2::
	msgbox HogTown_Text_Totodile2, MSGBOX_NPC
	end
HogTown_Text_Totodile2::
	.string "Toto\n"
	.string "Totodile!\p"
	.string "Toto...dile! dile!$"

HogTown_EventScript_Totodile3::
	msgbox HogTown_Text_Totodile3, MSGBOX_NPC
	end
HogTown_Text_Totodile3::
	.string "...toto$"

	