name: CI

on:
  push:
    branches:
      - master
      - upcoming
  pull_request:

jobs:
  build:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    if: github.actor != 'allcontributors[bot]'
=======
>>>>>>> parent of 7263bb1886 (Update CI to ignore allcontributors commits (#7046))
=======
>>>>>>> parent of 7263bb1886 (Update CI to ignore allcontributors commits (#7046))
=======
    if: github.actor != 'allcontributors'
>>>>>>> parent of fd90802a37 (Fixed CI issue introduced 7046 (#7072))
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      COMPARE: 0
      UNUSED_ERROR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi libpng-dev python3
        # build-essential and git are already installed

      - name: ROM
        env:
          COMPARE: 0
        run: make -j${nproc} -O all

      - name: Test
        env:
          TEST: 1
        run: |
          make -j${nproc} check
<<<<<<< HEAD
<<<<<<< HEAD
  allcontributors:
    if: github.actor == 'allcontributors'
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Automatically pass for allcontributors
        run: echo "CI automatically passes for allcontributors" && exit 0

=======
>>>>>>> parent of 7263bb1886 (Update CI to ignore allcontributors commits (#7046))
=======
>>>>>>> parent of 7263bb1886 (Update CI to ignore allcontributors commits (#7046))
