name: Labels

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  label:
<<<<<<< HEAD
    if: github.actor != 'allcontributors[bot]'
=======
>>>>>>> parent of 7263bb1886 (Update CI to ignore allcontributors commits (#7046))
    runs-on: ubuntu-latest
    steps:
      - name: check labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: |
            General
            General Merge
            category: ability
            category: battle-ai
            category: battle-mechanic
            category: battle-tests
            category: items
            category: move animation
            category: move effect
            category: overworld
            category: pokemon
            category: sprite-issue
            type: documentation
<<<<<<< HEAD
  allcontributors:
    if: github.actor == 'allcontributors[bot]'
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Automatically pass for allcontributors
        run: echo "CI automatically passes for allcontributors" && exit 0

=======
>>>>>>> parent of 7263bb1886 (Update CI to ignore allcontributors commits (#7046))
